import unittest

from core.colors.color_identity import ColorIdentity


class TestColorIdentity(unittest.TestCase):
    # region Orderings
    wubrg_order = [
        ColorIdentity.C,
        ColorIdentity.W, ColorIdentity.U, ColorIdentity.B, ColorIdentity.R, ColorIdentity.G,
        ColorIdentity.WU, ColorIdentity.WB, ColorIdentity.WR, ColorIdentity.WG, ColorIdentity.UB,
        ColorIdentity.UR, ColorIdentity.UG, ColorIdentity.BR, ColorIdentity.BG, ColorIdentity.RG,
        ColorIdentity.WUB, ColorIdentity.WUR, ColorIdentity.WUG, ColorIdentity.WBR, ColorIdentity.WBG,
        ColorIdentity.WRG, ColorIdentity.UBR, ColorIdentity.UBG, ColorIdentity.URG, ColorIdentity.BRG,
        ColorIdentity.WUBR, ColorIdentity.WUBG, ColorIdentity.WURG, ColorIdentity.WBRG, ColorIdentity.UBRG,
        ColorIdentity.WUBRG,
    ]

    pentad_order = [
        ColorIdentity.C,
        ColorIdentity.W, ColorIdentity.U, ColorIdentity.B, ColorIdentity.R, ColorIdentity.G,
        ColorIdentity.WU, ColorIdentity.UB, ColorIdentity.BR, ColorIdentity.RG, ColorIdentity.WG,
        ColorIdentity.WB, ColorIdentity.BG, ColorIdentity.UG, ColorIdentity.UR, ColorIdentity.WR,
        ColorIdentity.WUR, ColorIdentity.UBG, ColorIdentity.WBR, ColorIdentity.URG, ColorIdentity.WBG,
        ColorIdentity.WUB, ColorIdentity.UBR, ColorIdentity.BRG, ColorIdentity.WRG, ColorIdentity.WUG,
        ColorIdentity.WUBR, ColorIdentity.WUBG, ColorIdentity.WURG, ColorIdentity.WBRG, ColorIdentity.UBRG,
        ColorIdentity.WUBRG,
    ]

    deck_order = [
        ColorIdentity.W, ColorIdentity.U, ColorIdentity.B, ColorIdentity.R, ColorIdentity.G,
        ColorIdentity.WU, ColorIdentity.WB, ColorIdentity.WR, ColorIdentity.WG, ColorIdentity.UB,
        ColorIdentity.UR, ColorIdentity.UG, ColorIdentity.BR, ColorIdentity.BG, ColorIdentity.RG,
        ColorIdentity.WUB, ColorIdentity.WUR, ColorIdentity.WUG, ColorIdentity.WBR, ColorIdentity.WBG,
        ColorIdentity.WRG, ColorIdentity.UBR, ColorIdentity.UBG, ColorIdentity.URG, ColorIdentity.BRG,
        ColorIdentity.WUBR, ColorIdentity.WUBG, ColorIdentity.WURG, ColorIdentity.WBRG, ColorIdentity.UBRG,
        ColorIdentity.WUBRG, ColorIdentity.C,
    ]

    value_order = [
        ColorIdentity.C, ColorIdentity.W, ColorIdentity.U, ColorIdentity.WU, ColorIdentity.B, ColorIdentity.WB,
        ColorIdentity.UB, ColorIdentity.WUB, ColorIdentity.R, ColorIdentity.WR, ColorIdentity.UR,
        ColorIdentity.WUR, ColorIdentity.BR, ColorIdentity.WBR, ColorIdentity.UBR, ColorIdentity.WUBR,
        ColorIdentity.G, ColorIdentity.WG, ColorIdentity.UG, ColorIdentity.WUG, ColorIdentity.BG,
        ColorIdentity.WBG, ColorIdentity.UBG, ColorIdentity.WUBG, ColorIdentity.RG, ColorIdentity.WRG,
        ColorIdentity.URG, ColorIdentity.WURG, ColorIdentity.BRG, ColorIdentity.WBRG, ColorIdentity.UBRG,
        ColorIdentity.WUBRG,
    ]
    # endregion Orderings

    def test_color_identity_iter(self):
        # NOTE: This test is _key_. If this fails, the basis of multiple functions is incorrect.
        self.assertListEqual(self.wubrg_order, [ci for ci in ColorIdentity])

    def test_sorting(self):
        ids = [ci for ci in ColorIdentity]
        self.assertListEqual(self.value_order, sorted(ids, key=lambda x: x.value))
        self.assertListEqual(self.wubrg_order, sorted(ids, key=lambda x: x.wubrg_idx))
        self.assertListEqual(self.pentad_order, sorted(ids, key=lambda x: x.pentad_idx))
        self.assertListEqual(self.deck_order, sorted(ids, key=lambda x: x.deck_idx))

    def test_by_name(self):
        self.assertEqual(ColorIdentity.C, ColorIdentity.by_name(''))
        self.assertEqual(ColorIdentity.C, ColorIdentity.by_name('C'))
        self.assertEqual(ColorIdentity.W, ColorIdentity.by_name('W'))
        self.assertEqual(ColorIdentity.W, ColorIdentity.by_name('White'))
        self.assertEqual(ColorIdentity.W, ColorIdentity.by_name('MonoWhite'))
        self.assertEqual(ColorIdentity.W, ColorIdentity.by_name('Ardenvale'))
        self.assertEqual(ColorIdentity.W, ColorIdentity.by_name('Auriok'))
        self.assertEqual(ColorIdentity.U, ColorIdentity.by_name('U'))
        self.assertEqual(ColorIdentity.U, ColorIdentity.by_name('Blue'))
        self.assertEqual(ColorIdentity.U, ColorIdentity.by_name('MonoBlue'))
        self.assertEqual(ColorIdentity.U, ColorIdentity.by_name('Vantress'))
        self.assertEqual(ColorIdentity.U, ColorIdentity.by_name('Neurok'))
        self.assertEqual(ColorIdentity.B, ColorIdentity.by_name('B'))
        self.assertEqual(ColorIdentity.B, ColorIdentity.by_name('Black'))
        self.assertEqual(ColorIdentity.B, ColorIdentity.by_name('MonoBlack'))
        self.assertEqual(ColorIdentity.B, ColorIdentity.by_name('Locthwain'))
        self.assertEqual(ColorIdentity.B, ColorIdentity.by_name('Moriok'))
        self.assertEqual(ColorIdentity.R, ColorIdentity.by_name('R'))
        self.assertEqual(ColorIdentity.R, ColorIdentity.by_name('Red'))
        self.assertEqual(ColorIdentity.R, ColorIdentity.by_name('MonoRed'))
        self.assertEqual(ColorIdentity.R, ColorIdentity.by_name('Embereth'))
        self.assertEqual(ColorIdentity.R, ColorIdentity.by_name('Vulshok'))
        self.assertEqual(ColorIdentity.G, ColorIdentity.by_name('G'))
        self.assertEqual(ColorIdentity.G, ColorIdentity.by_name('Green'))
        self.assertEqual(ColorIdentity.G, ColorIdentity.by_name('MonoGreen'))
        self.assertEqual(ColorIdentity.G, ColorIdentity.by_name('Garenbrig'))
        self.assertEqual(ColorIdentity.G, ColorIdentity.by_name('Sylvok'))
        self.assertEqual(ColorIdentity.WU, ColorIdentity.by_name('WU'))
        self.assertEqual(ColorIdentity.WU, ColorIdentity.by_name('Azorius'))
        self.assertEqual(ColorIdentity.WU, ColorIdentity.by_name('Ojutai'))
        self.assertEqual(ColorIdentity.WB, ColorIdentity.by_name('WB'))
        self.assertEqual(ColorIdentity.WB, ColorIdentity.by_name('Orzhov'))
        self.assertEqual(ColorIdentity.WB, ColorIdentity.by_name('Silverquill'))
        self.assertEqual(ColorIdentity.WR, ColorIdentity.by_name('WR'))
        self.assertEqual(ColorIdentity.WR, ColorIdentity.by_name('Boros'))
        self.assertEqual(ColorIdentity.WR, ColorIdentity.by_name('Lorehold'))
        self.assertEqual(ColorIdentity.WG, ColorIdentity.by_name('WG'))
        self.assertEqual(ColorIdentity.WG, ColorIdentity.by_name('Selesnya'))
        self.assertEqual(ColorIdentity.WG, ColorIdentity.by_name('Dromoka'))
        self.assertEqual(ColorIdentity.UB, ColorIdentity.by_name('UB'))
        self.assertEqual(ColorIdentity.UB, ColorIdentity.by_name('Dimir'))
        self.assertEqual(ColorIdentity.UB, ColorIdentity.by_name('Silumgar'))
        self.assertEqual(ColorIdentity.UR, ColorIdentity.by_name('UR'))
        self.assertEqual(ColorIdentity.UR, ColorIdentity.by_name('Izzet'))
        self.assertEqual(ColorIdentity.UR, ColorIdentity.by_name('Prismari'))
        self.assertEqual(ColorIdentity.UG, ColorIdentity.by_name('UG'))
        self.assertEqual(ColorIdentity.UG, ColorIdentity.by_name('Simic'))
        self.assertEqual(ColorIdentity.UG, ColorIdentity.by_name('Quandrix'))
        self.assertEqual(ColorIdentity.BR, ColorIdentity.by_name('BR'))
        self.assertEqual(ColorIdentity.BR, ColorIdentity.by_name('Rakdos'))
        self.assertEqual(ColorIdentity.BR, ColorIdentity.by_name('Kolaghan'))
        self.assertEqual(ColorIdentity.BG, ColorIdentity.by_name('BG'))
        self.assertEqual(ColorIdentity.BG, ColorIdentity.by_name('Golgari'))
        self.assertEqual(ColorIdentity.BG, ColorIdentity.by_name('Witherbloom'))
        self.assertEqual(ColorIdentity.RG, ColorIdentity.by_name('RG'))
        self.assertEqual(ColorIdentity.RG, ColorIdentity.by_name('Gruul'))
        self.assertEqual(ColorIdentity.RG, ColorIdentity.by_name('Atarka'))
        self.assertEqual(ColorIdentity.WUB, ColorIdentity.by_name('WUB'))
        self.assertEqual(ColorIdentity.WUB, ColorIdentity.by_name('Esper'))
        self.assertEqual(ColorIdentity.WUB, ColorIdentity.by_name('Obscura'))
        self.assertEqual(ColorIdentity.WUR, ColorIdentity.by_name('WUR'))
        self.assertEqual(ColorIdentity.WUR, ColorIdentity.by_name('Jeskai'))
        self.assertEqual(ColorIdentity.WUR, ColorIdentity.by_name('Raugrin'))
        self.assertEqual(ColorIdentity.WUR, ColorIdentity.by_name('Numot'))
        self.assertEqual(ColorIdentity.WUR, ColorIdentity.by_name('Raka'))
        self.assertEqual(ColorIdentity.WUG, ColorIdentity.by_name('WUG'))
        self.assertEqual(ColorIdentity.WUG, ColorIdentity.by_name('Bant'))
        self.assertEqual(ColorIdentity.WUG, ColorIdentity.by_name('Brokers'))
        self.assertEqual(ColorIdentity.WBR, ColorIdentity.by_name('WBR'))
        self.assertEqual(ColorIdentity.WBR, ColorIdentity.by_name('Mardu'))
        self.assertEqual(ColorIdentity.WBR, ColorIdentity.by_name('Savai'))
        self.assertEqual(ColorIdentity.WBR, ColorIdentity.by_name('Oros'))
        self.assertEqual(ColorIdentity.WBR, ColorIdentity.by_name('Dega'))
        self.assertEqual(ColorIdentity.WBG, ColorIdentity.by_name('WBG'))
        self.assertEqual(ColorIdentity.WBG, ColorIdentity.by_name('Abzan'))
        self.assertEqual(ColorIdentity.WBG, ColorIdentity.by_name('Indatha'))
        self.assertEqual(ColorIdentity.WBG, ColorIdentity.by_name('Teneb'))
        self.assertEqual(ColorIdentity.WBG, ColorIdentity.by_name('Necra'))
        self.assertEqual(ColorIdentity.WRG, ColorIdentity.by_name('WRG'))
        self.assertEqual(ColorIdentity.WRG, ColorIdentity.by_name('Naya'))
        self.assertEqual(ColorIdentity.WRG, ColorIdentity.by_name('Cabaretti'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.by_name('UBR'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.by_name('Grixis'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.by_name('Maestros'))
        self.assertEqual(ColorIdentity.UBG, ColorIdentity.by_name('UBG'))
        self.assertEqual(ColorIdentity.UBG, ColorIdentity.by_name('Sultai'))
        self.assertEqual(ColorIdentity.UBG, ColorIdentity.by_name('Zagoth'))
        self.assertEqual(ColorIdentity.UBG, ColorIdentity.by_name('Vorosh'))
        self.assertEqual(ColorIdentity.UBG, ColorIdentity.by_name('Ana'))
        self.assertEqual(ColorIdentity.URG, ColorIdentity.by_name('URG'))
        self.assertEqual(ColorIdentity.URG, ColorIdentity.by_name('Temur'))
        self.assertEqual(ColorIdentity.URG, ColorIdentity.by_name('Ketria'))
        self.assertEqual(ColorIdentity.URG, ColorIdentity.by_name('Intet'))
        self.assertEqual(ColorIdentity.URG, ColorIdentity.by_name('Ceta'))
        self.assertEqual(ColorIdentity.BRG, ColorIdentity.by_name('BRG'))
        self.assertEqual(ColorIdentity.BRG, ColorIdentity.by_name('Jund'))
        self.assertEqual(ColorIdentity.BRG, ColorIdentity.by_name('Riveteers'))
        self.assertEqual(ColorIdentity.WUBR, ColorIdentity.by_name('WUBR'))
        self.assertEqual(ColorIdentity.WUBR, ColorIdentity.by_name('Yore'))
        self.assertEqual(ColorIdentity.WUBR, ColorIdentity.by_name('Artifice'))
        self.assertEqual(ColorIdentity.WUBR, ColorIdentity.by_name('NonG'))
        self.assertEqual(ColorIdentity.WUBG, ColorIdentity.by_name('WUBG'))
        self.assertEqual(ColorIdentity.WUBG, ColorIdentity.by_name('Witch'))
        self.assertEqual(ColorIdentity.WUBG, ColorIdentity.by_name('Growth'))
        self.assertEqual(ColorIdentity.WUBG, ColorIdentity.by_name('NonR'))
        self.assertEqual(ColorIdentity.WURG, ColorIdentity.by_name('WURG'))
        self.assertEqual(ColorIdentity.WURG, ColorIdentity.by_name('Ink'))
        self.assertEqual(ColorIdentity.WURG, ColorIdentity.by_name('Altruism'))
        self.assertEqual(ColorIdentity.WURG, ColorIdentity.by_name('NonB'))
        self.assertEqual(ColorIdentity.WBRG, ColorIdentity.by_name('WBRG'))
        self.assertEqual(ColorIdentity.WBRG, ColorIdentity.by_name('Dune'))
        self.assertEqual(ColorIdentity.WBRG, ColorIdentity.by_name('Aggression'))
        self.assertEqual(ColorIdentity.WBRG, ColorIdentity.by_name('NonU'))
        self.assertEqual(ColorIdentity.UBRG, ColorIdentity.by_name('UBRG'))
        self.assertEqual(ColorIdentity.UBRG, ColorIdentity.by_name('Glint'))
        self.assertEqual(ColorIdentity.UBRG, ColorIdentity.by_name('Chaos'))
        self.assertEqual(ColorIdentity.UBRG, ColorIdentity.by_name('NonW'))
        self.assertEqual(ColorIdentity.WUBRG, ColorIdentity.by_name('WUBRG'))
        self.assertEqual(ColorIdentity.WUBRG, ColorIdentity.by_name('FiveColor'))
        self.assertEqual(ColorIdentity.WUBRG, ColorIdentity.by_name('All'))

    def test_get(self):
        # TODO: Test the get class method, which is a more forgiving factory method.
        #  How forgiving the method should be still needs to be considered more.
        # TODO: Fix the get method, as custom Literals cannot be used with typechecks.
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.get('UBR'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.get('Grixis'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.get('GRIXIS'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.get('grixis'))
        self.assertEqual(ColorIdentity.UBR, ColorIdentity.get('GrIxIs'))

    def test_inclusion(self):
        self.assertIn(ColorIdentity.C, ColorIdentity.C)
        self.assertIn(ColorIdentity.C, ColorIdentity.U)
        self.assertIn(ColorIdentity.C, ColorIdentity.UR)
        self.assertIn(ColorIdentity.C, ColorIdentity.URG)
        self.assertIn(ColorIdentity.C, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.C, ColorIdentity.WUBRG)
        self.assertNotIn(ColorIdentity.U, ColorIdentity.C)
        self.assertIn(ColorIdentity.U, ColorIdentity.U)
        self.assertIn(ColorIdentity.U, ColorIdentity.UR)
        self.assertIn(ColorIdentity.U, ColorIdentity.URG)
        self.assertIn(ColorIdentity.U, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.U, ColorIdentity.WUBRG)
        self.assertNotIn(ColorIdentity.UR, ColorIdentity.C)
        self.assertNotIn(ColorIdentity.UR, ColorIdentity.U)
        self.assertIn(ColorIdentity.UR, ColorIdentity.UR)
        self.assertIn(ColorIdentity.UR, ColorIdentity.URG)
        self.assertIn(ColorIdentity.UR, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.UR, ColorIdentity.WUBRG)
        self.assertNotIn(ColorIdentity.URG, ColorIdentity.C)
        self.assertNotIn(ColorIdentity.URG, ColorIdentity.U)
        self.assertNotIn(ColorIdentity.URG, ColorIdentity.UR)
        self.assertIn(ColorIdentity.URG, ColorIdentity.URG)
        self.assertIn(ColorIdentity.URG, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.URG, ColorIdentity.WUBRG)
        self.assertNotIn(ColorIdentity.WURG, ColorIdentity.C)
        self.assertNotIn(ColorIdentity.WURG, ColorIdentity.U)
        self.assertNotIn(ColorIdentity.WURG, ColorIdentity.UR)
        self.assertNotIn(ColorIdentity.WURG, ColorIdentity.URG)
        self.assertIn(ColorIdentity.WURG, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.WURG, ColorIdentity.WUBRG)
        self.assertNotIn(ColorIdentity.WUBRG, ColorIdentity.C)
        self.assertNotIn(ColorIdentity.WUBRG, ColorIdentity.U)
        self.assertNotIn(ColorIdentity.WUBRG, ColorIdentity.UR)
        self.assertNotIn(ColorIdentity.WUBRG, ColorIdentity.URG)
        self.assertNotIn(ColorIdentity.WUBRG, ColorIdentity.WURG)
        self.assertIn(ColorIdentity.WUBRG, ColorIdentity.WUBRG)

    def test_get_color_combinations(self):
        self.assertListEqual(self.wubrg_order, ColorIdentity.get_color_combinations())
        self.assertListEqual(self.wubrg_order[0:1], ColorIdentity.get_color_combinations(0, 0))
        self.assertListEqual(self.wubrg_order[1:6], ColorIdentity.get_color_combinations(1, 1))
        self.assertListEqual(self.wubrg_order[6:16], ColorIdentity.get_color_combinations(2, 2))
        self.assertListEqual(self.wubrg_order[16:26], ColorIdentity.get_color_combinations(3, 3))
        self.assertListEqual(self.wubrg_order[26:31], ColorIdentity.get_color_combinations(4, 4))
        self.assertListEqual(self.wubrg_order[31:32], ColorIdentity.get_color_combinations(5, 5))
        self.assertListEqual(self.wubrg_order[0:26], ColorIdentity.get_color_combinations(0, 3))
        self.assertListEqual(self.wubrg_order[26:32], ColorIdentity.get_color_combinations(4, 5))

        self.assertListEqual(self.wubrg_order[1:6], ColorIdentity.colors())
        self.assertListEqual(ColorIdentity.get_color_combinations(1, 1), ColorIdentity.colors())

    def test_exact(self):
        self.assertListEqual(ColorIdentity.C.exact, [ColorIdentity.C])
        self.assertListEqual(ColorIdentity.W.exact, [ColorIdentity.W])
        self.assertListEqual(ColorIdentity.U.exact, [ColorIdentity.U])
        self.assertListEqual(ColorIdentity.B.exact, [ColorIdentity.B])
        self.assertListEqual(ColorIdentity.R.exact, [ColorIdentity.R])
        self.assertListEqual(ColorIdentity.G.exact, [ColorIdentity.G])
        self.assertListEqual(ColorIdentity.WU.exact, [ColorIdentity.WU])
        self.assertListEqual(ColorIdentity.WB.exact, [ColorIdentity.WB])
        self.assertListEqual(ColorIdentity.WR.exact, [ColorIdentity.WR])
        self.assertListEqual(ColorIdentity.WG.exact, [ColorIdentity.WG])
        self.assertListEqual(ColorIdentity.UB.exact, [ColorIdentity.UB])
        self.assertListEqual(ColorIdentity.UR.exact, [ColorIdentity.UR])
        self.assertListEqual(ColorIdentity.UG.exact, [ColorIdentity.UG])
        self.assertListEqual(ColorIdentity.BR.exact, [ColorIdentity.BR])
        self.assertListEqual(ColorIdentity.BG.exact, [ColorIdentity.BG])
        self.assertListEqual(ColorIdentity.RG.exact, [ColorIdentity.RG])
        self.assertListEqual(ColorIdentity.WUB.exact, [ColorIdentity.WUB])
        self.assertListEqual(ColorIdentity.WUR.exact, [ColorIdentity.WUR])
        self.assertListEqual(ColorIdentity.WUG.exact, [ColorIdentity.WUG])
        self.assertListEqual(ColorIdentity.WBR.exact, [ColorIdentity.WBR])
        self.assertListEqual(ColorIdentity.WBG.exact, [ColorIdentity.WBG])
        self.assertListEqual(ColorIdentity.WRG.exact, [ColorIdentity.WRG])
        self.assertListEqual(ColorIdentity.UBR.exact, [ColorIdentity.UBR])
        self.assertListEqual(ColorIdentity.UBG.exact, [ColorIdentity.UBG])
        self.assertListEqual(ColorIdentity.URG.exact, [ColorIdentity.URG])
        self.assertListEqual(ColorIdentity.BRG.exact, [ColorIdentity.BRG])
        self.assertListEqual(ColorIdentity.WUBR.exact, [ColorIdentity.WUBR])
        self.assertListEqual(ColorIdentity.WUBG.exact, [ColorIdentity.WUBG])
        self.assertListEqual(ColorIdentity.WURG.exact, [ColorIdentity.WURG])
        self.assertListEqual(ColorIdentity.WBRG.exact, [ColorIdentity.WBRG])
        self.assertListEqual(ColorIdentity.UBRG.exact, [ColorIdentity.UBRG])
        self.assertListEqual(ColorIdentity.WUBRG.exact, [ColorIdentity.WUBRG])

    def test_subset(self):
        # TODO: Expand these tests to cover more (all?) colour combinations.
        self.assertListEqual(ColorIdentity.C.subset, [ColorIdentity.C])
        self.assertListEqual(ColorIdentity.W.subset, [ColorIdentity.C, ColorIdentity.W])
        self.assertListEqual(ColorIdentity.WUBRG.subset, self.wubrg_order)

    def test_superset(self):
        # TODO: Expand these tests to cover  more (all?) colour combinations.
        self.assertListEqual(ColorIdentity.C.superset, self.wubrg_order)
        self.assertListEqual(ColorIdentity.WUBRG.superset, [ColorIdentity.WUBRG])

    def test_adjacent(self):
        # TODO: Expand these tests to cover  more (all?) colour combinations.
        self.assertListEqual(ColorIdentity.C.adjacent, self.wubrg_order[0:6])
        # self.assertListEqual(ColorIdentity.WUBRG.adjacent(), [ColorIdentity.WUBRG] + self.wubrg_order[26:31])

    def test_shares(self):
        # TODO: Expand these tests to cover  more (all?) colour combinations.
        self.assertListEqual(ColorIdentity.C.shares, [])
        self.assertListEqual(ColorIdentity.WUBRG.shares, self.wubrg_order[1:])

    def test_set_likes(self):
        self.test_exact()
        self.test_subset()
        self.test_superset()
        self.test_adjacent()
        self.test_shares()

    def test_aliases(self):
        self.assertListEqual(ColorIdentity.C.aliases, ['C', ''])
        self.assertListEqual(ColorIdentity.W.aliases, ['W', 'White', 'MonoWhite', 'Ardenvale', 'Auriok'])
        self.assertListEqual(ColorIdentity.U.aliases, ['U', 'Blue', 'MonoBlue', 'Vantress', 'Neurok'])
        self.assertListEqual(ColorIdentity.B.aliases, ['B', 'Black', 'MonoBlack', 'Locthwain', 'Moriok'])
        self.assertListEqual(ColorIdentity.R.aliases, ['R', 'Red', 'MonoRed', 'Embereth', 'Vulshok'])
        self.assertListEqual(ColorIdentity.G.aliases, ['G', 'Green', 'MonoGreen', 'Garenbrig', 'Sylvok'])
        self.assertListEqual(ColorIdentity.WU.aliases, ['WU', 'Azorius', 'Ojutai'])
        self.assertListEqual(ColorIdentity.WB.aliases, ['WB', 'Orzhov', 'Silverquill'])
        self.assertListEqual(ColorIdentity.WR.aliases, ['WR', 'Boros', 'Lorehold'])
        self.assertListEqual(ColorIdentity.WG.aliases, ['WG', 'Selesnya', 'Dromoka'])
        self.assertListEqual(ColorIdentity.UB.aliases, ['UB', 'Dimir', 'Silumgar'])
        self.assertListEqual(ColorIdentity.UR.aliases, ['UR', 'Izzet', 'Prismari'])
        self.assertListEqual(ColorIdentity.UG.aliases, ['UG', 'Simic', 'Quandrix'])
        self.assertListEqual(ColorIdentity.BR.aliases, ['BR', 'Rakdos', 'Kolaghan'])
        self.assertListEqual(ColorIdentity.BG.aliases, ['BG', 'Golgari', 'Witherbloom'])
        self.assertListEqual(ColorIdentity.RG.aliases, ['RG', 'Gruul', 'Atarka'])
        self.assertListEqual(ColorIdentity.WUB.aliases, ['WUB', 'Esper', 'Obscura'])
        self.assertListEqual(ColorIdentity.WUR.aliases, ['WUR', 'Jeskai', 'Raugrin', 'Numot', 'Raka'])
        self.assertListEqual(ColorIdentity.WUG.aliases, ['WUG', 'Bant', 'Brokers'])
        self.assertListEqual(ColorIdentity.WBR.aliases, ['WBR', 'Mardu', 'Savai', 'Oros', 'Dega'])
        self.assertListEqual(ColorIdentity.WBG.aliases, ['WBG', 'Abzan', 'Indatha', 'Teneb', 'Necra'])
        self.assertListEqual(ColorIdentity.WRG.aliases, ['WRG', 'Naya', 'Cabaretti'])
        self.assertListEqual(ColorIdentity.UBR.aliases, ['UBR', 'Grixis', 'Maestros'])
        self.assertListEqual(ColorIdentity.UBG.aliases, ['UBG', 'Sultai', 'Zagoth', 'Vorosh', 'Ana'])
        self.assertListEqual(ColorIdentity.URG.aliases, ['URG', 'Temur', 'Ketria', 'Intet', 'Ceta'])
        self.assertListEqual(ColorIdentity.BRG.aliases, ['BRG', 'Jund', 'Riveteers'])
        self.assertListEqual(ColorIdentity.WUBR.aliases, ['WUBR', 'Yore', 'Artifice', 'NonG'])
        self.assertListEqual(ColorIdentity.WUBG.aliases, ['WUBG', 'Witch', 'Growth', 'NonR'])
        self.assertListEqual(ColorIdentity.WURG.aliases, ['WURG', 'Ink', 'Altruism', 'NonB'])
        self.assertListEqual(ColorIdentity.WBRG.aliases, ['WBRG', 'Dune', 'Aggression', 'NonU'])
        self.assertListEqual(ColorIdentity.UBRG.aliases, ['UBRG', 'Glint', 'Chaos', 'NonW'])
        self.assertListEqual(ColorIdentity.WUBRG.aliases, ['WUBRG', 'FiveColor', 'All'])

    def test_iter(self):
        c = ColorIdentity.C
        w = ColorIdentity.W
        u = ColorIdentity.U
        b = ColorIdentity.B
        r = ColorIdentity.R
        g = ColorIdentity.G
        self.assertListEqual(list(ColorIdentity.C.__iter__()), [c])
        self.assertListEqual(list(ColorIdentity.W.__iter__()), [w])
        self.assertListEqual(list(ColorIdentity.U.__iter__()), [u])
        self.assertListEqual(list(ColorIdentity.B.__iter__()), [b])
        self.assertListEqual(list(ColorIdentity.R.__iter__()), [r])
        self.assertListEqual(list(ColorIdentity.G.__iter__()), [g])
        self.assertListEqual(list(ColorIdentity.WU.__iter__()), [w, u])
        self.assertListEqual(list(ColorIdentity.WB.__iter__()), [w, b])
        self.assertListEqual(list(ColorIdentity.WR.__iter__()), [w, r])
        self.assertListEqual(list(ColorIdentity.WG.__iter__()), [w, g])
        self.assertListEqual(list(ColorIdentity.UB.__iter__()), [u, b])
        self.assertListEqual(list(ColorIdentity.UR.__iter__()), [u, r])
        self.assertListEqual(list(ColorIdentity.UG.__iter__()), [u, g])
        self.assertListEqual(list(ColorIdentity.BR.__iter__()), [b, r])
        self.assertListEqual(list(ColorIdentity.BG.__iter__()), [b, g])
        self.assertListEqual(list(ColorIdentity.RG.__iter__()), [r, g])
        self.assertListEqual(list(ColorIdentity.WUB.__iter__()), [w, u, b])
        self.assertListEqual(list(ColorIdentity.WUR.__iter__()), [w, u, r])
        self.assertListEqual(list(ColorIdentity.WUG.__iter__()), [w, u, g])
        self.assertListEqual(list(ColorIdentity.WBR.__iter__()), [w, b, r])
        self.assertListEqual(list(ColorIdentity.WBG.__iter__()), [w, b, g])
        self.assertListEqual(list(ColorIdentity.WRG.__iter__()), [w, r, g])
        self.assertListEqual(list(ColorIdentity.UBR.__iter__()), [u, b, r])
        self.assertListEqual(list(ColorIdentity.UBG.__iter__()), [u, b, g])
        self.assertListEqual(list(ColorIdentity.URG.__iter__()), [u, r, g])
        self.assertListEqual(list(ColorIdentity.BRG.__iter__()), [b, r, g])
        self.assertListEqual(list(ColorIdentity.WUBR.__iter__()), [w, u, b, r])
        self.assertListEqual(list(ColorIdentity.WUBG.__iter__()), [w, u, b, g])
        self.assertListEqual(list(ColorIdentity.WURG.__iter__()), [w, u, r, g])
        self.assertListEqual(list(ColorIdentity.WBRG.__iter__()), [w, b, r, g])
        self.assertListEqual(list(ColorIdentity.UBRG.__iter__()), [u, b, r, g])
        self.assertListEqual(list(ColorIdentity.WUBRG.__iter__()), [w, u, b, r, g])
        pass

    def test_str(self):
        self.assertEqual(ColorIdentity.C.__str__(), '')
        self.assertEqual(ColorIdentity.W.__str__(), 'W')
        self.assertEqual(ColorIdentity.White.__str__(), 'W')
        self.assertEqual(ColorIdentity.MonoWhite.__str__(), 'W')
        self.assertEqual(ColorIdentity.Ardenvale.__str__(), 'W')
        self.assertEqual(ColorIdentity.Auriok.__str__(), 'W')
        self.assertEqual(ColorIdentity.U.__str__(), 'U')
        self.assertEqual(ColorIdentity.Blue.__str__(), 'U')
        self.assertEqual(ColorIdentity.MonoBlue.__str__(), 'U')
        self.assertEqual(ColorIdentity.Vantress.__str__(), 'U')
        self.assertEqual(ColorIdentity.Neurok.__str__(), 'U')
        self.assertEqual(ColorIdentity.B.__str__(), 'B')
        self.assertEqual(ColorIdentity.Black.__str__(), 'B')
        self.assertEqual(ColorIdentity.MonoBlack.__str__(), 'B')
        self.assertEqual(ColorIdentity.Locthwain.__str__(), 'B')
        self.assertEqual(ColorIdentity.Moriok.__str__(), 'B')
        self.assertEqual(ColorIdentity.R.__str__(), 'R')
        self.assertEqual(ColorIdentity.Red.__str__(), 'R')
        self.assertEqual(ColorIdentity.MonoRed.__str__(), 'R')
        self.assertEqual(ColorIdentity.Embereth.__str__(), 'R')
        self.assertEqual(ColorIdentity.Vulshok.__str__(), 'R')
        self.assertEqual(ColorIdentity.G.__str__(), 'G')
        self.assertEqual(ColorIdentity.Green.__str__(), 'G')
        self.assertEqual(ColorIdentity.MonoGreen.__str__(), 'G')
        self.assertEqual(ColorIdentity.Garenbrig.__str__(), 'G')
        self.assertEqual(ColorIdentity.Sylvok.__str__(), 'G')
        self.assertEqual(ColorIdentity.WU.__str__(), 'WU')
        self.assertEqual(ColorIdentity.Azorius.__str__(), 'WU')
        self.assertEqual(ColorIdentity.Ojutai.__str__(), 'WU')
        self.assertEqual(ColorIdentity.WB.__str__(), 'WB')
        self.assertEqual(ColorIdentity.Orzhov.__str__(), 'WB')
        self.assertEqual(ColorIdentity.Silverquill.__str__(), 'WB')
        self.assertEqual(ColorIdentity.WR.__str__(), 'WR')
        self.assertEqual(ColorIdentity.Boros.__str__(), 'WR')
        self.assertEqual(ColorIdentity.Lorehold.__str__(), 'WR')
        self.assertEqual(ColorIdentity.WG.__str__(), 'WG')
        self.assertEqual(ColorIdentity.Selesnya.__str__(), 'WG')
        self.assertEqual(ColorIdentity.Dromoka.__str__(), 'WG')
        self.assertEqual(ColorIdentity.UB.__str__(), 'UB')
        self.assertEqual(ColorIdentity.Dimir.__str__(), 'UB')
        self.assertEqual(ColorIdentity.Silumgar.__str__(), 'UB')
        self.assertEqual(ColorIdentity.UR.__str__(), 'UR')
        self.assertEqual(ColorIdentity.Izzet.__str__(), 'UR')
        self.assertEqual(ColorIdentity.Prismari.__str__(), 'UR')
        self.assertEqual(ColorIdentity.UG.__str__(), 'UG')
        self.assertEqual(ColorIdentity.Simic.__str__(), 'UG')
        self.assertEqual(ColorIdentity.Quandrix.__str__(), 'UG')
        self.assertEqual(ColorIdentity.BR.__str__(), 'BR')
        self.assertEqual(ColorIdentity.Rakdos.__str__(), 'BR')
        self.assertEqual(ColorIdentity.Kolaghan.__str__(), 'BR')
        self.assertEqual(ColorIdentity.BG.__str__(), 'BG')
        self.assertEqual(ColorIdentity.Golgari.__str__(), 'BG')
        self.assertEqual(ColorIdentity.Witherbloom.__str__(), 'BG')
        self.assertEqual(ColorIdentity.RG.__str__(), 'RG')
        self.assertEqual(ColorIdentity.Gruul.__str__(), 'RG')
        self.assertEqual(ColorIdentity.Atarka.__str__(), 'RG')
        self.assertEqual(ColorIdentity.WUB.__str__(), 'WUB')
        self.assertEqual(ColorIdentity.Esper.__str__(), 'WUB')
        self.assertEqual(ColorIdentity.Obscura.__str__(), 'WUB')
        self.assertEqual(ColorIdentity.WUR.__str__(), 'WUR')
        self.assertEqual(ColorIdentity.Jeskai.__str__(), 'WUR')
        self.assertEqual(ColorIdentity.Raugrin.__str__(), 'WUR')
        self.assertEqual(ColorIdentity.Numot.__str__(), 'WUR')
        self.assertEqual(ColorIdentity.Raka.__str__(), 'WUR')
        self.assertEqual(ColorIdentity.WUG.__str__(), 'WUG')
        self.assertEqual(ColorIdentity.Bant.__str__(), 'WUG')
        self.assertEqual(ColorIdentity.Brokers.__str__(), 'WUG')
        self.assertEqual(ColorIdentity.WBR.__str__(), 'WBR')
        self.assertEqual(ColorIdentity.Mardu.__str__(), 'WBR')
        self.assertEqual(ColorIdentity.Savai.__str__(), 'WBR')
        self.assertEqual(ColorIdentity.Oros.__str__(), 'WBR')
        self.assertEqual(ColorIdentity.Dega.__str__(), 'WBR')
        self.assertEqual(ColorIdentity.WBG.__str__(), 'WBG')
        self.assertEqual(ColorIdentity.Abzan.__str__(), 'WBG')
        self.assertEqual(ColorIdentity.Indatha.__str__(), 'WBG')
        self.assertEqual(ColorIdentity.Teneb.__str__(), 'WBG')
        self.assertEqual(ColorIdentity.Necra.__str__(), 'WBG')
        self.assertEqual(ColorIdentity.WRG.__str__(), 'WRG')
        self.assertEqual(ColorIdentity.Naya.__str__(), 'WRG')
        self.assertEqual(ColorIdentity.Cabaretti.__str__(), 'WRG')
        self.assertEqual(ColorIdentity.UBR.__str__(), 'UBR')
        self.assertEqual(ColorIdentity.Grixis.__str__(), 'UBR')
        self.assertEqual(ColorIdentity.Maestros.__str__(), 'UBR')
        self.assertEqual(ColorIdentity.UBG.__str__(), 'UBG')
        self.assertEqual(ColorIdentity.Sultai.__str__(), 'UBG')
        self.assertEqual(ColorIdentity.Zagoth.__str__(), 'UBG')
        self.assertEqual(ColorIdentity.Vorosh.__str__(), 'UBG')
        self.assertEqual(ColorIdentity.Ana.__str__(), 'UBG')
        self.assertEqual(ColorIdentity.URG.__str__(), 'URG')
        self.assertEqual(ColorIdentity.Temur.__str__(), 'URG')
        self.assertEqual(ColorIdentity.Ketria.__str__(), 'URG')
        self.assertEqual(ColorIdentity.Intet.__str__(), 'URG')
        self.assertEqual(ColorIdentity.Ceta.__str__(), 'URG')
        self.assertEqual(ColorIdentity.BRG.__str__(), 'BRG')
        self.assertEqual(ColorIdentity.Jund.__str__(), 'BRG')
        self.assertEqual(ColorIdentity.Riveteers.__str__(), 'BRG')
        self.assertEqual(ColorIdentity.WUBR.__str__(), 'WUBR')
        self.assertEqual(ColorIdentity.Yore.__str__(), 'WUBR')
        self.assertEqual(ColorIdentity.Artifice.__str__(), 'WUBR')
        self.assertEqual(ColorIdentity.NonG.__str__(), 'WUBR')
        self.assertEqual(ColorIdentity.WUBG.__str__(), 'WUBG')
        self.assertEqual(ColorIdentity.Witch.__str__(), 'WUBG')
        self.assertEqual(ColorIdentity.Growth.__str__(), 'WUBG')
        self.assertEqual(ColorIdentity.NonR.__str__(), 'WUBG')
        self.assertEqual(ColorIdentity.WURG.__str__(), 'WURG')
        self.assertEqual(ColorIdentity.Ink.__str__(), 'WURG')
        self.assertEqual(ColorIdentity.Altruism.__str__(), 'WURG')
        self.assertEqual(ColorIdentity.NonB.__str__(), 'WURG')
        self.assertEqual(ColorIdentity.WBRG.__str__(), 'WBRG')
        self.assertEqual(ColorIdentity.Dune.__str__(), 'WBRG')
        self.assertEqual(ColorIdentity.Aggression.__str__(), 'WBRG')
        self.assertEqual(ColorIdentity.NonU.__str__(), 'WBRG')
        self.assertEqual(ColorIdentity.UBRG.__str__(), 'UBRG')
        self.assertEqual(ColorIdentity.Glint.__str__(), 'UBRG')
        self.assertEqual(ColorIdentity.Chaos.__str__(), 'UBRG')
        self.assertEqual(ColorIdentity.NonW.__str__(), 'UBRG')
        self.assertEqual(ColorIdentity.WUBRG.__str__(), 'WUBRG')
        self.assertEqual(ColorIdentity.FiveColor.__str__(), 'WUBRG')
        self.assertEqual(ColorIdentity.All.__str__(), 'WUBRG')
